
version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: db_kvas
    environment:
      POSTGRES_DB: "clientdb"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_pass"
    ports:
      - "5432:5432"