
version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: "db_name"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_pass"
    ports:
      - "5432:5432"